services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: themrityunjaypathak/churnlabs-api:v1
    container_name: churn-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    image: themrityunjaypathak/churnlabs-frontend:v1
    container_name: churn-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped
